export const dogBreeds = [
  {
    id: 1,
    name: "Labrador Retriever",
    origin: "Canada",
    size: "Large",
    lifespan: "10-12 years",
    temperament: "Friendly, Active, Outgoing",
    grooming: "Low",
    exercise: "High",
    diet: "Standard",
    healthIssues: "Hip dysplasia, obesity",
    energyLevel: "High",
    hypoallergenic: false,
    image: "https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9",
  },
  {
    id: 2,
    name: "German Shepherd",
    origin: "Germany",
    size: "Large",
    lifespan: "9-13 years",
    temperament: "Confident, Courageous, Smart",
    grooming: "Medium",
    exercise: "High",
    diet: "Standard",
    healthIssues: "Hip dysplasia, bloat",
    energyLevel: "High",
    hypoallergenic: false,
    image: "https://images.unsplash.com/photo-1589941013456-b599de8436f6",
  },
  {
    id: 3,
    name: "Poodle",
    origin: "Germany",
    size: "Medium",
    lifespan: "12-15 years",
    temperament: "Intelligent, Active, Alert",
    grooming: "High",
    exercise: "Medium",
    diet: "Standard",
    healthIssues: "Hip dysplasia, eye problems",
    energyLevel: "Medium",
    hypoallergenic: true,
    image: "https://images.unsplash.com/photo-1594149929911-78975a43d4f5",
  },
  {
    id: 4,
    name: "Beagle",
    origin: "England",
    size: "Small",
    lifespan: "12-15 years",
    temperament: "Friendly, Curious, Merry",
    grooming: "Low",
    exercise: "Medium",
    diet: "Standard",
    healthIssues: "Obesity, epilepsy",
    energyLevel: "Medium",
    hypoallergenic: false,
    image: "https://images.unsplash.com/photo-1505628346881-b72b27e84530",
  },
];
